### ISSUE TITLE
auto-complete only works with id number or first word of issue description

### ISSUE THREAD

**Issue by priocomsolutions** [nenes25/mantisbt_autosuggest#6]
The autocomplete feature works great with issue ID, but if you try searching with issue description it only works when you can remember the first word in the issue description

**Comment by priocomsolutions** [comment]
> The autocomplete feature works great with issue ID, but if you try searching with issue description it only works when you can remember the first word in the issue description

Any assistance please?

**Comment by nenes25** [comment]
Hi,
Juste replace the content of the line https://github.com/nenes25/mantisbt_autosuggest/blob/master/AutoSuggest/pages/get-suggestions.php#L47 by  OR summary LIKE '%". $t_search . "%'  and it should works ;)

Regards,

**Comment by priocomsolutions** [comment]
Hello,
It works like a charm. Thank you so much!

And thanks again for creating the plugin, it has helped our workflow a lot.

Best regards.
[image: logo+name+mantra-final.png]
Priocom Solutions Limited.
Email: priocomsolutions@gmail.com

**Comment by nenes25** [comment]
Thanks for your return, your suggestion was a good one :)
So I've implemented it for everyone.
Nice to know that it could help !
Regards,
